config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/uses"=>"customers#index"
    resources :genres do
        get :search
    end

    resources :items
    resources :evaluation, only: [:index, :destroy]
  end
  scope module: :user do
    root to: "homes#top"
  end
  namespace :user do
    resources :items do
      resources :evaluations, only: [:new, :create, :index,  :update]
    end
    #resources :users do
      #collection do
        #get :delete
        #get :search
      #end
    #end

    get "/my_page"=>"users#show"
    get "/information/edit"=>"users#edit"
    patch "/information"=>"users#update"
    get "/unsubscribe"=>"users#unsubscribe"
    get '/genre/search' => 'genres#search'
    resources :items, only: [:index, :show]

    #root to: "homes#top"
    root to: redirect('/')
    get "/about"=>"homes#about"
     # 論理削除用のルーティング
    patch  '/withdraw' => 'users#withdraw'
  end
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def new
    @genre = Genre.new
  end
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save!
    flash[:notice] = "ジャンルの追加に成功しました。"
    redirect_to admin_genres_path
    else
    flash[:alert] = "ジャンルの追加に失敗しました。"
    @genres = Genre.all
    render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
    flash[:success] = "ジャンルの更新に成功しました。"
    redirect_to admin_genres_path
    else
    flash.now[:alert] = "ジャンルの更新に失敗しました。"
    render :edit
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    flash[:deleted] = "ジャンルの削除に成功しました。"
    @genres = Genre.all  # ジャンルの一覧を再取得して@genresに代入
    redirect_to admin_genres_path
  end

  def search
    @genres = Genre.all
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end

  private
  def genre_params
    params.require(:genre).permit(:name,:item_id,:genre)
  end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  def search
    @genres = Genre.all
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <h1>ジャンル編集</h1>
    <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch  do |form| %>
    <div>
    <%= form.label :name, "ジャンル名" %>
    <%= form.text_field :name %>
    </div>
    <div>
    <%= form.submit "更新" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1>ジャンル追加</h1>
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <h4>ジャンル名</h4>
      <%= f.text_field :name %>
      <%= f.submit "ジャンルを追加する" %>
      <%end%>
      <h1>ジャンル一覧</h1>
      <% @genres.each do |genre| %>
      <div><%= genre.name %></div>
      <%= link_to '編集', edit_admin_genre_path(genre) %>
      <%= link_to '削除', admin_genre_path(genre), method: :delete, data: { confirm: '本当に削除しますか？' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/search.html.erb
<%= render 'shared/items', title: "検索結果",
                           role: "admin",
                           genres: @genres,
                           items: @items %>