config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/uses"=>"customers#index"
    resources :genres do
        get :search
    end

    resources :items
    resources :evaluation, only: [:index, :destroy]
  end
  scope module: :user do
    root to: "homes#top"
  end
  namespace :user do
    resources :items do
      resources :evaluations, only: [:new, :create, :index,  :update]
    end
    #resources :users do
      #collection do
        #get :delete
        #get :search
      #end
    #end

    get "/my_page"=>"users#show"
    get "/information/edit"=>"users#edit"
    patch "/information"=>"users#update"
    get "/unsubscribe"=>"users#unsubscribe"
    get '/genre/search' => 'genres#search'
    resources :items, only: [:index, :show]

    #root to: "homes#top"
    root to: redirect('/')
    get "/about"=>"homes#about"
     # 論理削除用のルーティング
    patch  '/withdraw' => 'users#withdraw'
  end
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :evaluations, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true
  validates :age, presence: true
  validates :skin_quality, presence: true

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/customers_controller.rb
class User::CustomersController < ApplicationController
  before_action :authenticate_user!
  def show
    # 自分のあかうんとを取得
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    # 送られてきたぱらめーたを保存
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      sign_in(@user, bypass: true)
      redirect_to user_my_page_path
    else
      flash.now[:alert] = "ユーザー情報の更新に失敗しました"
      render :edit
    end
  end

  def unsubscribe
    @user = current_user
    @user.status = "退会"
    @user.save
    
  end

  def withdrawal
  end

  protected
    def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :skin_quality, :skin_trouble)
    end
end

app/controllers/user/evaluations_controller.rb
class User::EvaluationsController < ApplicationController
  before_action :authenticate_user!

  def new
    #新しい評価を作成するためのインスタンス変数を作成
    @evaluation = Evaluation.new
  end

  def create
    #ユーザーが入力した評価情報を使用して、評価を作成
    @evaluation = current_user.evaluations.new(evaluation_params)
     # 評価に関連付けられたアイテムを取得
    @item = Item.find(evaluation_params[:item_id])
    #評価の保存が成功した場合
    if @evaluation.save
      flash[:notice] = "レビューの追加に成功しました。"
      #評価を表示するためのパスにリダイレクト
      redirect_to user_item_path(@item)
    else
      flash.now[:alert] = "レビューの追加に失敗しました。"
      #評価の作成フォームを含むアイテムの詳細ページが再表示
      @item = Item.find(params[:evaluation][:item_id])
      @evaluations = @item.evaluations
      render "user/items/show"
    end
  end

  #def update
    #@evaluation = current_user.evaluations.new(evaluation_params)
    #if @evaluation.update(evaluation_params)
     # flash[:success] = "レビューの編集に成功しました。"
      #redirect_to user_item_path(@evaluation)
    #else
      #flash.now[:alert] = "レビューの編集に失敗しました。"
      #render update
    #end
  #end

  #def edit
    #@evaluation = Evaluation.find(params[:id])
  #end

  def index
    #全てのアイテムを取得してインスタンス変数に保存
    @evaluations = Evaluation.all
    @evaluation = Evaluation.new
  end

  #def show
    #@evaluation = Evaluation.find(params[:id])
  #end

  #def destroy
    #@evaluation =Evaluation.find(params[:id])
    #@evaluation.destroy
    #flash[:deleted] = "レビューの削除に成功しました。"
    #redirect_to user_item_path
  #end

  private

    def evaluation_params
      params.require(:evaluation).permit(:content, :item_id)
    end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  def search
    @genres = Genre.all
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController

  def index
    @items = Item.all
    @genres = Genre.all
  end

  def show
    #評価を作成するためのインスタンス変数
    @evaluation = Evaluation.new
    #指定されたアイテムと
    @item = Item.find(params[:id])
    #それに関連する評価を取得
    @evaluations = @item.evaluations
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    user_items_path
  end
  
  protected
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :age, :skin_quality, :skin_trouble])
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  before_action :reject_end_user, only: [:create]
  def after_sign_in_path_for(resource)
    user_items_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end

  private
  # 退会しているかいないかを判断するメソッド
  def reject_end_user
  # 入力されたemailからアカウントを1件取得
    @end_user = User.find_by(email: params[:user][:email])

    if @end_user
      #有効なパスワードであるが、退会済みである場合
      if @end_user.valid_password?(params[:user][:password]) && (@end_user.is_deleted == true)

        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください"
        redirect_to new_user_registration_path
      #入力ミスによるユーザーが見つからない場合
      else
        flash[:notice] = "項目を再入力してください"
      end
    else
      #登録がまだな場合
      flash[:notice] = "該当するユーザーが見つかりません。新規登録をお願いします。"
    end
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    # 自分のあかうんとを取得
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    # 送られてきたぱらめーたを保存
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      sign_in(@user, bypass: true)
      redirect_to user_my_page_path
    else
      flash.now[:alert] = "ユーザー情報の更新に失敗しました"
      render :edit
    end
  end

  def unsubscribe
    @user = current_user

  end

  def withdraw
    @user = User.find(current_user.id)
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to user_root_path
  end

  protected
    def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :skin_quality, :skin_trouble)
    end
end

app/helpers/user/customers_helper.rb
module User::CustomersHelper
end

app/helpers/user/evaluations_helper.rb
module User::EvaluationsHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/items_helper.rb
module User::ItemsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">

<%= form_with model: @user, url: user_information_path, method: :patch do |f| %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name, value: @user.name, autofocus: true, autocomplete: "name" %>
  </div>

  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, value: @user.email, autofocus: true, autocomplete: "email" %>
  </div>

  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div>
    <%= f.label :age %><br />
    <%= f.select :age, (10..90).step(10), selected: @user.age, prompt: "年齢を選択してください" %>
  </div>

  <div>
    <%= f.label :skin_quality %><br />
    <%= f.select :skin_quality, ['乾燥肌', '混合肌', '脂性肌'], selected: @user.skin_quality, prompt: "肌質を選択してください" %>
  </div>

  <div>
    <%= f.label :skin_trouble %><br />
    <%= f.select :skin_trouble, ['ニキビ', 'シミ', 'シワ', '乾燥','特になし'], selected: @user.skin_trouble, prompt: "肌トラブルを選択してください" %>
  </div>

  <div>
    <%= f.submit "更新する" %>
  </div>
  <div>
    <%= link_to "マイページに戻る", user_my_page_path %>
  </div>
  <div>
    <%= link_to "退会する", user_unsubscribe_path, class: "btn btn-danger" %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class="container">
  
  <h1>マイページ</h1>
  
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>名前</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>email</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>age</th>
            <td><%= @user.age %></td>
          </tr>
          <tr>
            <th>肌質</th>
            <td><%= @user.skin_quality %></td>
          </tr>
          <tr>
            <th>肌トラブル</th>
            <td><%= @user.skin_trouble %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to '編集する', user_information_edit_path %>
</div>
          

app/views/user/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <p>本当に退会されますか？</br>
       退会された場合同じメールアドレスでの再度ご登録はできません。</br>
       ご了承ください。</p>
      <div class="actions">
        <%= link_to "退会する", user_withdraw_path,method: :patch, class: "btn btn-danger" %>
        <%= link_to "退会しない", user_information_edit_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>